version: '3.4'

services:
  auth-service:
    container_name: "auth-service"
    build: ./authentication-service
    environment:
      - PORT=80
      - AUTH_CALLBACK_URL=/auth/callback
      - AUTH_SECRET=J4W5_Sy5T3M
      - SHRAGA_URL=http://13.79.7.3
      - CLIENT_URL=http://permission-service:3000
      - AUTH_TOKEN=kd-token
    ports:
      - 80:80
  
  permission-service:
    container_name: "permission-service"
    build: ./permission-service
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://<user>:<password>@cluster0.eckmd.mongodb.net/users
      - MONGO_COLLECTION_NAME=users
      - SCHEMA_API_HOST=schema-api-mock:4000
      - INSTANCE_API_HOST=instance-api-mock:5000
      - GENERAL_ACCESS_PERMISSION_ID=0
      - GET_ALL_USERS_PERMISSION_ID=1
      - GET_CURRENT_USER_PERMISSION_ID=2
      - GET_USER_BY_ID_PERMISSION_ID=3
      - CREATE_USER_PERMISSION_ID=4
      - UPDATE_USER_PERMISSION_ID=5
      - DELETE_USER_PERMISSION_ID=6
    ports:
      - 3000:3000
  
  schema-api-mock:
    container_name: "schema-api-mock"
    build: ./api-mock
    environment:
      - PORT=4000
      - SERVICE_NAME=Schema
    ports:
      - 4000:4000
  
  instance-api-mock:
    container_name: "instance-api-mock"
    build: ./api-mock
    environment:
      - PORT=5000
      - SERVICE_NAME=Instance
    ports:
      - 5000:5000
